[AzureBatch]
PoolNameBase = 'pl' #namming convention is {PoolNameBase}-{''.join(random.choices(alphabet, k=4))}-{PoolVMSku}-{PoolVMSpotInstanceCount + PoolVMDedicatedInstanceCount}-{TaskSlotsPerTask}
UniquePoolNameFlag = 'true'
TaskSlotsPerTask = 1 
PoolVMSku = 'STANDARD_A2_V2' #BASIC_A2 https://azure.microsoft.com/en-us/pricing/details/batch/
Publisher="microsoft-azure-batch"
Offer="ubuntu-server-container"
Sku="20-04-lts"
DropPoolOnCompletionFlag = 'false'


[DataGeneration]
ConfigFilePath = 'config_user_local.toml'


[PythonCommands]
NodeSetup.commands = ['echo "sudo apt update && sudo apt upgrade -y"'
            ,'sudo apt update && sudo apt upgrade -y'
            ,'sudo apt install unzip'
            
            #Install python 3.11
            ,'sudo add-apt-repository ppa:deadsnakes/ppa -y'
            ,'echo "sudo apt install python3.11 -y"'
            ,'sudo apt install python3.11 -y'
            ,'sudo apt update'

            #Install pip for python 3.11
            ,'echo "sudo apt-get install -y python3-pip"'
            ,'sudo apt-get install -y python3-pip'
            ,'curl -sS https://bootstrap.pypa.io/get-pip.py | python3.11'

            #Download code artifacts from github
            ,'sudo rm -rf /mnt/batch/tasks/shared/Event-Hub-Throughput-Generator.zip'
            ,'sudo rm -rf /mnt/batch/tasks/shared/Event-Hub-Throughput-Generator'
            ,'curl -H "Accept: application/octet-stream" https://github.com/bretamyers/Event-Hub-Throughput-Generator/archive/master.zip -L -o /mnt/batch/tasks/shared/Event-Hub-Throughput-Generator.zip'
            ,'unzip -o /mnt/batch/tasks/shared/Event-Hub-Throughput-Generator.zip -d /mnt/batch/tasks/shared/Event-Hub-Throughput-Generator'

            #Install requirement python packages
            ,'python3.11 -m pip install -r /mnt/batch/tasks/shared/Event-Hub-Throughput-Generator/Event-Hub-Throughput-Generator-main/requirements.txt'
        ] 
CodeSetup.commands = ['rm -rf /mnt/batch/tasks/shared/Event-Hub-Throughput-Generator.zip'
            ,'rm -rf /mnt/batch/tasks/shared/Event-Hub-Throughput-Generator'
            ,'curl -H "Accept: application/octet-stream" https://github.com/bretamyers/Event-Hub-Throughput-Generator/archive/master.zip -L -o /mnt/batch/tasks/shared/Event-Hub-Throughput-Generator.zip'
            ,'unzip -o /mnt/batch/tasks/shared/Event-Hub-Throughput-Generator.zip -d /mnt/batch/tasks/shared/Event-Hub-Throughput-Generator'
            ,'cd /mnt/batch/tasks/shared/Event-Hub-Throughput-Generator/Event-Hub-Throughput-Generator-main/'
            #Install requirement python packages
            ,'python3.11 -m pip install -r /mnt/batch/tasks/shared/Event-Hub-Throughput-Generator/Event-Hub-Throughput-Generator-main/requirements.txt'
        ]

VMSetup.commandsGit = ['echo "sudo apt update && sudo apt upgrade -y"'
            ,'sudo apt update && sudo apt upgrade -y'
            
            #Install python 3.11
            ,'sudo add-apt-repository ppa:deadsnakes/ppa -y'
            ,'echo "sudo apt install python3.11 -y"'
            ,'sudo apt install python3.11 -y'
            ,'sudo apt update'

            #Install pip for python 3.11
            ,'echo "sudo apt-get install -y python3-pip"'
            ,'sudo apt-get install -y python3-pip'
            ,'curl -sS https://bootstrap.pypa.io/get-pip.py | python3.11'

            #Download code artifacts from github
            ,'sudo rm -rf /mnt/batch/tasks/shared/Event-Hub-Throughput-Generator'
            ,'git clone https://github.com/bretamyers/Event-Hub-Throughput-Generator /mnt/batch/tasks/shared/Event-Hub-Throughput-Generator'
            
            #Install requirement python packages
            ,'python3.11 -m pip install -r /mnt/batch/tasks/shared/Event-Hub-Throughput-Generator/requirements.txt'
        ] 
CodeSetup.commandsGit = ['rm -rf /mnt/batch/tasks/shared/Event-Hub-Throughput-Generator'
            ,'git clone https://github.com/bretamyers/Event-Hub-Throughput-Generator /mnt/batch/tasks/shared/Event-Hub-Throughput-Generator'
            ,'cd /mnt/batch/tasks/shared/Event-Hub-Throughput-Generator'
            #Install requirement python packages
            ,'python3.11 -m pip install -r /mnt/batch/tasks/shared/Event-Hub-Throughput-Generator/requirements.txt'
        ]

PythonRepoPath = '/mnt/batch/tasks/shared/Event-Hub-Throughput-Generator/Event-Hub-Throughput-Generator-main'
PythonProgramFilePath = 'main/GenerateData.py'



