[AzureBatch]
BatchAccountName = 'batchbrmyers'
BatchAccountKey = 'tPI6i/HR2aEXoU6xwhH0bl3tyU4QzmBRkST+YMRzVc6U5j+yv62ZpLDRHKpzHgIaZaRg0sfxcuwn+ABaPsFnEg=='
BatchServiceUrl = 'https://batchbrmyers.eastus2.batch.azure.com'
PoolNameBase = 'pool' #namming convention is {PoolNameBase}-{PoolVMSku}-{PoolVMSpotInstanceCount + PoolVMDedicatedInstanceCount}-{TaskSlotsPerTask}
TaskSlotsPerTask = 1 #Should I take out??
PoolVMSku = 'STANDARD_A2_V2' # https://azure.microsoft.com/en-us/pricing/details/batch/
ThroughputMessagesPerSec = 1000
EventHubConnection = 'Endpoint=sb://eventhubnamespacebam.servicebus.windows.net/;SharedAccessKeyName=policyManage;SharedAccessKey=r0MWD563SwTrRijfETLf2BttZD4eQItiq+AEhKSh/Lc='
EventHubName = 'myvehiclehub'
RunDurationMin = 10

[PythonCommands]
VMSetup.commands = ['echo "sudo apt update && sudo apt upgrade -y"'
            ,'sudo apt update && sudo apt upgrade -y'
            ,'sudo apt install unzip'
            #,'sleep 120' #wait 2 minutes
            
            #Install python 3.11
            ,'sudo add-apt-repository ppa:deadsnakes/ppa -y'
            ,'echo "sudo apt install python3.11 -y"'
            ,'sudo apt install python3.11 -y'
            ,'sudo apt update'

            #Install pip for python 3.11
            ,'echo "sudo apt-get install -y python3-pip"'
            ,'sudo apt-get install -y python3-pip'
            ,'curl -sS https://bootstrap.pypa.io/get-pip.py | python3.11'

            #Download code artifacts from github
            ,'curl -H "Authorization: token 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" -H "Accept: application/octet-stream" https://github.com/bretamyers/EventHub-Throughput-Generator/archive/master.zip -L -o /mnt/batch/tasks/shared/EventHub-Throughput-Generator.zip'
            ,'unzip -o /mnt/batch/tasks/shared/EventHub-Throughput-Generator.zip -d /mnt/batch/tasks/shared/EventHub-Throughput-Generator'
            
            #Install requirement python packages
            ,'python3.11 -m pip install -r /mnt/batch/tasks/shared/EventHub-Throughput-Generator/EventHub-Throughput-Generator-main/requirements.txt'
        ] 
CodeSetup.commands = ['curl -H "Authorization: token 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" -H "Accept: application/octet-stream" https://github.com/bretamyers/EventHub-Throughput-Generator/archive/master.zip -L -o /mnt/batch/tasks/shared/EventHub-Throughput-Generator.zip'
            ,'rm -r /mnt/batch/tasks/shared/EventHub-Throughput-Generator'
            ,'unzip /mnt/batch/tasks/shared/EventHub-Throughput-Generator.zip -d /mnt/batch/tasks/shared/EventHub-Throughput-Generator'
            ,'cd /mnt/batch/tasks/shared/EventHub-Throughput-Generator/EventHub-Throughput-Generator-main/'
        ]

PythonRunFilePath = 'main/GenerateData.py'


