# https://github.com/microsoft/sql-server-samples/tree/master/samples/databases/wide-world-importers
# https://dataedo.com/samples/html/WideWorldImporters/doc/WideWorldImporters_5/modules/Sales_110/module.html
WideWorldImporters = '''{
    "SalesTransaction": {
        "Invoice": {
            "InvoiceID": "{guid}"
            ,"InvoiceDate": "{datetime}"
            ,"ConfirmedDeliveryTime": "{datetime}"
            ,"InvoiceDate": "{datetime}"
            ,"Customer": {
                "CustomerID": "{datetime}"
                ,"DeliveryCityID": "{datetime}"
            }
            ,"BillToCustomerID": "{datetime}"
            ,"SalespersonPersonID": "{datetime}"
            ,"InvoiceLines": [
                {
                    ,"Description": "{datetime}"
                    ,"Quantity": "{datetime}"
                    ,"UnitPrice": "{datetime}"
                    ,"TaxRate": "{datetime}"
                    ,"ExtendedPrice": "{datetime}"
                    ,"TaxAmount": "{datetime}"
                    ,"LineProfit": "{datetime}"
                    ,"StockItems": {
                        "StockItemID": "{datetime}"
                        ,"IsChillerStock": "{datetime}"
                    }
                    ,"PackageTypes": {
                        "PackageTypeID": "{datetime}"
                        ,"PackageTypeName": "{datetime}"
                    }
                }]
        }
}
'''

