
# https://hl7.org/fhir/devicemetric-example.json.html
FHIR_DeviceMetric = '''{
  "resourceType": "DeviceMetric",
  "id": "example",
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p><b>Generated Narrative</b></p><div style=\"display: inline-block; background-color: #d9e0e7; padding: 6px; margin: 4px; border: 1px solid #8da1b4; border-radius: 5px; line-height: 60%\"><p style=\"margin-bottom: 0px\">Resource &quot;example&quot; </p></div><p><b>identifier</b>: id: 345675</p><p><b>type</b>: MDC_PULS_OXIM_SAT_O2 <span style=\"background: LightGoldenRodYellow; margin: 4px; border: 1px solid khaki\"> (<a href=\"http://terminology.hl7.org/3.1.0/CodeSystem-v3-mdc.html\">ISO 11073-10101 Health informatics - Point-of-care</a>#150456)</span></p><p><b>unit</b>: MDC_DIM_PERCENT <span style=\"background: LightGoldenRodYellow; margin: 4px; border: 1px solid khaki\"> (<a href=\"http://terminology.hl7.org/3.1.0/CodeSystem-v3-mdc.html\">ISO 11073-10101 Health informatics - Point-of-care</a>#262688)</span></p><p><b>source</b>: <a href=\"todo.html\">Device/dev1</a></p><p><b>parent</b>: <a href=\"todo.html\">DeviceDefinition/dc102</a></p><p><b>operationalStatus</b>: on</p><p><b>color</b>: blue</p><p><b>category</b>: measurement</p><p><b>measurementPeriod</b>: Do Once per 1 seconds</p><h3>Calibrations</h3><table class=\"grid\"><tr><td>-</td><td><b>Type</b></td><td><b>State</b></td><td><b>Time</b></td></tr><tr><td>*</td><td>two-point</td><td>calibrated</td><td>29/12/2016 1:03:04 AM</td></tr></table></div>"
  },
  "identifier": [
    {
      "system": "http://goodcare.org/devicemetric/id",
      "value": "345675"
    }
  ],
  "type": {
    "coding": [
      {
        "system": "urn:iso:std:iso:11073:10101",
        "code": "150456",
        "display": "MDC_PULS_OXIM_SAT_O2"
      }
    ]
  },
  "unit": {
    "coding": [
      {
        "system": "urn:iso:std:iso:11073:10101",
        "code": "262688",
        "display": "MDC_DIM_PERCENT"
      }
    ]
  },
  "source": {
    "reference": "Device/dev1"
  },
  "parent": {
    "reference": "DeviceDefinition/dc102"
  },
  "operationalStatus": "on",
  "color": "blue",
  "category": "measurement",
  "measurementPeriod": {
    "repeat": {
      "frequency": 1,
      "period": 1,
      "periodUnit": "s"
    }
  },
  "calibration": [
    {
      "type": "two-point",
      "state": "calibrated",
      "time": "2016-12-28T09:03:04-05:00"
    }
  ]
}'''
